name: Run Tests and Lint Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: quote-builder

      - name: Run ESLint
        run: npx eslint .
        working-directory: quote-builder

      - name: Run Jest Tests
        run: npx jest
        working-directory: quote-builder
